export const dataOrang = [
  {
    id: "1",
    nama: "Abhinaya Nuzuluzzuhdi",
    kelompok: "1",
    motto: "Belajar dari masa lalu, berharap untuk masa depan",
    telepon: "085794551953",
    ttl: "Malang, 31 Oktober 2004",
    asal: "Malang, Jawa Timur",
  },
  {
    id: "2",
    nama: "Afgan Galih Fauz Amjad Amadinah",
    kelompok: "1",
    motto: "ONE",
    telepon: "085749577424",
    ttl: "Jakarta 11 Maret 2005",
    asal: "Bogor",
  },
  {
    id: "3",
    nama: "ANNISA",
    kelompok: "1",
    motto: "Ambil resiko atau kehilangan kesempatan",
    telepon: "081226561287",
    ttl: "Nganjuk, 01 Agustus 2004",
    asal: "Nganjuk",
  },
  {
    id: "4",
    nama: "Aqueena Regita Hapsari",
    kelompok: "1",
    motto: "Anak Tuhan Yesus selamanya",
    telepon: "08155162499",
    ttl: "Surabaya, 12 Februari 2005",
    asal: "Surabaya",
  },
  {
    id: "5",
    nama: "ARIMBI PUTRI HAPSARI",
    kelompok: "1",
    motto: "Berani ambil risiko, bermimpi besar, dan berharap besar.",
    telepon: "085852763041",
    ttl: "MAGETAN,04 MEI 2004",
    asal: "MAGETAN",
  },
  {
    id: "6",
    nama: "Azzahra Attaqina",
    kelompok: "1",
    motto: "Bermimpilah semaumu asal kamu bangun",
    telepon: "082264651009",
    ttl: "Situbondo,08 November 2004",
    asal: "Kota Malang",
  },
  {
    id: "7",
    nama: "Bayu Triwibowo",
    kelompok: "1",
    motto: "Temukan makna hidupmu sendiri",
    telepon: "087850048885",
    ttl: "Jayapura, 18 April 2004",
    asal: "Jombang",
  },
  {
    id: "8",
    nama: "CAKRA WANGSA MAY AHMAD WIDODO",
    kelompok: "1",
    motto: "GAS DULU BARU CURHAT",
    telepon: "081249471998",
    ttl: "Blitar, 5 Mei 2004",
    asal: "Blitar",
  },
  {
    id: "9",
    nama: "Charellino Kalingga Sadewo",
    kelompok: "1",
    motto: "Tetap semangat Jangan bersedih dan teruslah berusaha",
    telepon: "081331822287",
    ttl: "Batu,24 Desember 2004",
    asal: "Batu",
  },
  {
    id: "10",
    nama: "Devan Ksatria Utama",
    kelompok: "1",
    motto: "Jangan takut mengambil resiko",
    telepon: "089516477307",
    ttl: "Malang, 25 November 2005",
    asal: "Pasuruan, Jawa timur",
  },
  {
    id: "11",
    nama: "Dewi Sulistiyowati",
    kelompok: "1",
    motto: "sukses no 1, kamu akhir akhir aja",
    telepon: "081216877489",
    ttl: "Surabaya, 02 Juni 2005",
    asal: "Surabaya",
  },
  {
    id: "12",
    nama: "Ekya Muhammad Hasfi Fadlilurrahman",
    kelompok: "1",
    motto: "Apapun yang terjadi jangan lupa ngopi",
    telepon: "081252288955",
    ttl: "Bondowoso, 14 November 2004",
    asal: "Bondowoso",
  },
  {
    id: "13",
    nama: "Ericha Rizki Wardani",
    kelompok: "1",
    motto: "Jangan mimpikan hidupmu tapi hidupkanlah mimpimu",
    telepon: "085765991971",
    ttl: "Blitar, 22 September 2004",
    asal: "Blitar",
  },
  {
    id: "14",
    nama: "Erik Ridho Firmansyah",
    kelompok: "1",
    motto: "Jangan pernah menyerah meskipun terasa sulit",
    telepon: "085218994761",
    ttl: "10 Juli 2004",
    asal: "Probolinggo",
  },
  {
    id: "15",
    nama: "Fandy Wahyu Hanzura",
    kelompok: "1",
    motto: "kesuksesan itu pasti walalupun sering tertunda",
    telepon: "08993945716",
    ttl: "Kediri, 28 september 2005",
    asal: "Malang, Jawa Timur",
  },
  {
    id: "16",
    nama: "Firman Dzaki Rahman",
    kelompok: "1",
    motto: "Tetap hidup sampai ajal menjemput",
    telepon: "085174324054",
    ttl: "Tulungagung, 24 mei 2005",
    asal: "Blitar",
  },
  {
    id: "17",
    nama: "Gheriya Rahima Jauhar",
    kelompok: "1",
    motto: "Hidup enak, mati enak",
    telepon: "085231178688",
    ttl: "Situbondo, 23 Juli 2005",
    asal: "Situbondo",
  },
  {
    id: "18",
    nama: "Jiha Ramdhan",
    kelompok: "1",
    motto: "Sesungguhnya bersama Kesulitan, ada Kemudahan",
    telepon: "085817304152",
    ttl: "Malang, 10 November 2004",
    asal: "Malang",
  },
  {
    id: "19",
    nama: "Khuzaima Filla Januartha",
    kelompok: "1",
    motto:
      "Hidup adalah pertarungan, hanya ada 2 pilihan yaitu mengalahkan atau dikalahkan.",
    telepon: "082132517964",
    ttl: "17 Januari 2005",
    asal: "Dau Kabupaten Malang",
  },
  {
    id: "20",
    nama: "Luthfi Putra Mahardika",
    kelompok: "1",
    motto: "tugas selalu bersama mahasiswa",
    telepon: "081359045634",
    ttl: "Malang, 17 Agustus 2004",
    asal: "Malang",
  },
  {
    id: "21",
    nama: "MARGA RETA NOVIA PUTRI",
    kelompok: "1",
    motto: "whatever will be, will be.",
    telepon: "089529518500",
    ttl: "Malang, 19 November 2004",
    asal: "Malang",
  },
  {
    id: "22",
    nama: "MARSYA AURELIA SEFIRA",
    kelompok: "1",
    motto: "Utamakan attitude, karena attitude adalah kunci",
    telepon: "082337700758",
    ttl: "Malang, 08 April 2005",
    asal: "Malang",
  },
  {
    id: "23",
    nama: "MUCHAMMAD ARIEYA CANDRA PANGESTU",
    kelompok: "1",
    motto:
      "Jika kamu tak mengejar impianmu, kamu tak akan pernah memilikinya. Jika kamu tak melangkah maju, kamu akan selalu di tempat yang sama",
    telepon: "085333161642",
    ttl: "21 september 2004",
    asal: "Probolinggo",
  },
  {
    id: "24",
    nama: "Muhammad Akbar Fakhriy Daffa",
    kelompok: "1",
    motto: "You never walk alone",
    telepon: "081353727417",
    ttl: "10 Januari 2005",
    asal: "Kota kediri",
  },
  {
    id: "25",
    nama: "Muhammad Irsyad Dimas Abdillah",
    kelompok: "1",
    motto: "Hidup Seperti Larry",
    telepon: "085732915325",
    ttl: "Pasuruan, 15 Agustus 2004",
    asal: "Pasuruan",
  },
  {
    id: "26",
    nama: "Muhammad Reishi Fauzi Auguri",
    kelompok: "1",
    motto: "Do it now",
    telepon: "085773071834",
    ttl: "Jakarta, 24 Januari 2003",
    asal: "Bekasi",
  },
  {
    id: "27",
    nama: "MUHAMMAD SATRIA RAHMAD DAVID",
    kelompok: "1",
    motto: "Hidup itu simpel, tinggal nafas",
    telepon: "0895392594510",
    ttl: "17 Oktober 2004",
    asal: "Malang, Bumiayu, kecamatan Kedung kandang.",
  },
  {
    id: "28",
    nama: "MUHAMMAD TAQIYYUDDIN TSAQIF",
    kelompok: "1",
    motto: "jadikan usia orang tuamu sebagai saingan terberatmu",
    telepon: "089607088395",
    ttl: "Lamongan, 28 September 2004",
    asal: "Lamongan Jawa Timur",
  },
  {
    id: "29",
    nama: "Nadyne Rosalia Noer Azizah",
    kelompok: "1",
    motto: "Tidak ada kata Terlambat, Tetap berangkat walaupun Terlambat",
    telepon: "089638244477",
    ttl: "Malang, 10 Agustus 2005",
    asal: "Malang",
  },
  {
    id: "30",
    nama: "Nova Eliza Maharani",
    kelompok: "1",
    motto: "Setelah badai berlalu pasti akan ada pelangi indah yang menanti",
    telepon: "089523837769",
    ttl: "Malang, 10 November 2004",
    asal: "Malang",
  },
  {
    id: "31",
    nama: "Rayhan Heru Arifiansyah",
    kelompok: "1",
    motto: "Normal itu membosankan",
    telepon: "0811300529",
    ttl: "Malang, 30 Juni 2005",
    asal: "Malang",
  },
  {
    id: "32",
    nama: "Ridho Anfa'al",
    kelompok: "1",
    motto: "Sedikit bicara, banyak bekerja",
    telepon: "082132495749",
    ttl: "Malang, 13 Juni 2005",
    asal: "Malang",
  },
  {
    id: "33",
    nama: "Saka Nabil",
    kelompok: "1",
    motto: "hidup bukan saling mendahului, bermimpilah sendiri-sendiri",
    telepon: "087846242745",
    ttl: "Selong, 12 juni 2005",
    asal: "Lombok timur, NTB",
  },
  {
    id: "34",
    nama: "Saria Fauzani",
    kelompok: "1",
    motto: "Whatever you are, be a good one",
    telepon: "081515867380",
    ttl: "Nganjuk, 12 Juni 2004",
    asal: "Nganjuk",
  },
  {
    id: "35",
    nama: "Satrio Ahmad Ramadhani",
    kelompok: "1",
    motto: "Pandang semua dari sisi terbaik",
    telepon: "081998205455",
    ttl: "23-10-2005",
    asal: "Malang",
  },
  {
    id: "36",
    nama: "Siti Alifia Azzahra Mustofa",
    kelompok: "1",
    motto: "life is too short for fake butter, cheese, and people",
    telepon: "081216782134",
    ttl: "blitar, 28 feb 2005",
    asal: "malang",
  },
  {
    id: "37",
    nama: "TORA DIGDA KRISTIAWAN",
    kelompok: "1",
    motto: "be yourself end never be surrender",
    telepon: "085732445337",
    ttl: "18 april 2005",
    asal: "SIDOARJO",
  },
  {
    id: "38",
    nama: "Vidi Joshubzky Saviola",
    kelompok: "1",
    motto: "Everything Is Fine",
    telepon: "081216111668",
    ttl: "Yogyakarta, 3 Desember 2004",
    asal: "Kota Batu, Jawa Timur",
  },
  {
    id: "39",
    nama: "Adam Nur Alifi",
    kelompok: "1",
    motto: "Walau hidupmu berat dan penuh cobaan, yaudah aja sih",
    telepon: "083834410809",
    ttl: "Yogyakarta, 31 Januari 2003",
    asal: "Tulungagung",
  },
  {
    id: "40",
    nama: "ADNAN ARJU MAULANA PASHA",
    kelompok: "2",
    motto: "Kegagalan adalah keberhasilan yang tertunda",
    telepon: "081334828461",
    ttl: "Nganjuk, 14 februari 2004",
    asal: "Nganjuk",
  },
  {
    id: "41",
    nama: "Ahmad Ramadhan Baiakbar",
    kelompok: "2",
    motto:
      "Kegagalan adalah hal biasa, yang penting bagaimana cara kita menyikapinya. Kalau gagal maka evaluasi, perbaiki diri dan cobalah lagi. Keberhasilan akan datang pada mereka yang terus mencoba.",
    telepon: "085232104482",
    ttl: "Probolinggo, 09 November 2004",
    asal: "Kota Probolinggo",
  },
  {
    id: "42",
    nama: "Alyssa Tifara Y.",
    kelompok: "2",
    motto: "Berani ambil resiko, usaha tanpa batas, biar Tuhan yang menentukan",
    telepon: "081259380484",
    ttl: "Malang, 10 April 2005",
    asal: "Malang",
  },
  {
    id: "43",
    nama: "ANGGA AHMAD ROMANSA",
    kelompok: "2",
    motto: "no pain no gain",
    telepon: "0859350623281",
    ttl: "Surabaya,18 februari 2004",
    asal: "Blitar",
  },
  {
    id: "44",
    nama: "Aqil Rahmat Alifiandi",
    kelompok: "2",
    motto: "teruslah berusaha",
    telepon: "085868385754",
    ttl: "Malang, 14 juli 2005",
    asal: "Malang",
  },
  {
    id: "45",
    nama: "Aqila Nur Azza",
    kelompok: "2",
    motto: "Jadilah perubahan",
    telepon: "081230382286",
    ttl: "Kediri, 23 Februari 2005",
    asal: "Kabupaten Kediri",
  },
  {
    id: "46",
    nama: "Aqilla Aprily Kurnia Sari",
    kelompok: "2",
    motto: "Everything will pass",
    telepon: "082231720100",
    ttl: "Probolinggo, 2 April 2004",
    asal: "Probolinggo, Jawa Timur",
  },
  {
    id: "47",
    nama: "Ayleen Ruhul Qisthy",
    kelompok: "2",
    motto: "Tetap tersenyum",
    telepon: "088231322175",
    ttl: "Tulungagung, 27 Maret 2005",
    asal: "Tulungagung",
  },
  {
    id: "48",
    nama: "Candra Ahmad Dani",
    kelompok: "2",
    motto: "Nikmatilah hidup sebaik mungkin",
    telepon: "089517032681",
    ttl: "06-04-2004",
    asal: "Probolinggo",
  },
  {
    id: "49",
    nama: "Dhanisa Putri Mashilfa",
    kelompok: "2",
    motto: "akan ku hadapi semua tapi sambil nangis",
    telepon: "085733668226",
    ttl: "Surakarta, 02 September 2004",
    asal: "Bojonegoro",
  },
  {
    id: "50",
    nama: "Fahmi Yahya",
    kelompok: "2",
    motto: "Ketenangan adalah kunci kekuatan",
    telepon: "085895548401",
    ttl: "Tulungagung, 19 April 2004",
    asal: "Tulungagung",
  },
  {
    id: "51",
    nama: "Faishal Harist Rahmawan",
    kelompok: "2",
    motto: "Sukses muda kaya raya",
    telepon: "085708833141",
    ttl: "Kediri 26 Februari 2005",
    asal: "Ds. Jambean, Kec. Kras, Kab. Kediri",
  },
  {
    id: "52",
    nama: "Hamdan Azizul Hakim",
    kelompok: "2",
    motto: "jangan lupa sholat",
    telepon: "083850706596",
    ttl: "Sidoarjo, 24 Juni 2004",
    asal: "Malang",
  },
  {
    id: "53",
    nama: "Hanifah kurniasari",
    kelompok: "2",
    motto: "Bisa memimpin dan dipimpin",
    telepon: "082178174040",
    ttl: "Banyuasin, 05 Desember 2004",
    asal: "Palembang",
  },
  {
    id: "54",
    nama: "Hikmah Aldrin Abdillah",
    kelompok: "2",
    motto: "jika anda diremehkan, cukup diam dan buktikan",
    telepon: "081235373283",
    ttl: "Malang, 19 Mei 2005",
    asal: "Kota Malang",
  },
  {
    id: "55",
    nama: "Kamila Habiba Putri Ananta",
    kelompok: "2",
    motto: "Never give up",
    telepon: "085806916904",
    ttl: "Tulungagung, 26 April 2005",
    asal: "Tulungagung",
  },
  {
    id: "56",
    nama: "Lyra Faiqah Bilqis",
    kelompok: "2",
    motto:
      "Always give positive affirmations to yourself, because ability always begins with belief.",
    telepon: "081216548995",
    ttl: "Sidoarjo, 31 Juli 2004",
    asal: "Sidoarjo",
  },
  {
    id: "57",
    nama: "Mariska Putri",
    kelompok: "2",
    motto: "Berbuatlah baik tanpa perlu alasan",
    telepon: "081227818404",
    ttl: "Pati, 12 Agustus 2005",
    asal: "Pati, Jawa Tengah",
  },
  {
    id: "58",
    nama: "Maulana Rengga Ramadan",
    kelompok: "2",
    motto: "Tuhan bersama dengan orang-orang yang santai",
    telepon: "085708074515",
    ttl: "Sumenep 20 oktober 2004",
    asal: "Madura",
  },
  {
    id: "59",
    nama: "Michelle Dorani Shiba",
    kelompok: "2",
    motto: "Action is the basic key to all success",
    telepon: "085606319598",
    ttl: "Malang, 15 Juni 2005",
    asal: "Malang",
  },
  {
    id: "60",
    nama: "Muhammad Dimas Ajie Nugroho",
    kelompok: "2",
    motto: "Jika kamu takut gagal, kamu tidak pantas untuk sukses!",
    telepon: "082257165847",
    ttl: "Jombang, 16 Februari 2005",
    asal: "Jombang, Jawa Timur",
  },
  {
    id: "61",
    nama: "Muhammad Fairuz Daffa Athallah",
    kelompok: "2",
    motto: "Semangat membangun masadepan bangsa",
    telepon: "089697682479",
    ttl: "10 Juli 2005",
    asal: "Malang",
  },
  {
    id: "62",
    nama: "Muhammad Farrel Caesarian",
    kelompok: "2",
    motto: "no victory without sacrifice",
    telepon: "082132570837",
    ttl: "Malang, 27 Maret 2006",
    asal: "Malang",
  },
  {
    id: "63",
    nama: "Muhammad Khalid Atthoriq",
    kelompok: "2",
    motto: "live life above 7000rpm",
    telepon: "081230400332",
    ttl: "Malang, 10 November 2003",
    asal: "Malang",
  },
  {
    id: "64",
    nama: "Naufal Gajendra Ardiputra",
    kelompok: "2",
    motto: "jangan pantang menyerah terus berjuang",
    telepon: "085964363941",
    ttl: "Malang,02-Agustus-2004",
    asal: "Malang",
  },
  {
    id: "65",
    nama: "Putera Bhagaswara Raswidhyantoro",
    kelompok: "2",
    motto: "fokus pada tujuan, bukan hambatan",
    telepon: "08113033683",
    ttl: "Malang, 23 Mei 2003",
    asal: "Malang",
  },
  {
    id: "66",
    nama: "Rafi Ody Prasetyo",
    kelompok: "2",
    motto: "Janganlah hidup seperti newton, kebanyakan gaya",
    telepon: "085855564943",
    ttl: "Malang, 16 Juni 2003",
    asal: "Malang",
  },
  {
    id: "67",
    nama: "Rizky Roza Rahim",
    kelompok: "2",
    motto: "jika orang lain bisa, maka aku belum tentu",
    telepon: "08118032005",
    ttl: "JAKARTA, 27 MEI 2005",
    asal: "Bekasi",
  },
  {
    id: "68",
    nama: "Rizqi Dewanto Yumnaidzihar",
    kelompok: "2",
    motto: "Dont look back",
    telepon: "081217113659",
    ttl: "Malang 23 Desember 2004",
    asal: "Singosari Malang",
  },
  {
    id: "69",
    nama: "Satriyo Bagus Susianto",
    kelompok: "2",
    motto: "Fokus pada masa depan",
    telepon: "082132188004",
    ttl: "Tulungagung, 12 April 2005",
    asal: "Tulungagung, Jawa Timur",
  },
  {
    id: "70",
    nama: "soultan Mohammad Agnar Bisyarah",
    kelompok: "2",
    motto: "life is beautiful if you make it beautiful",
    telepon: "081275824927",
    ttl: "Maumere, 29 Maret 2005",
    asal: "Palangkaraya",
  },
  {
    id: "71",
    nama: "Veren Regina Tirsya",
    kelompok: "2",
    motto: "Tetaplah Berdoa",
    telepon: "081249135132",
    ttl: "Tulungagung, 22 November 2004",
    asal: "Tulungagung",
  },
  {
    id: "72",
    nama: "Yanuar Rizki Aminudin",
    kelompok: "2",
    motto: "Berusaha untuk kemajuan, bukan kesempurnaan",
    telepon: "089666832419",
    ttl: "Probolinggo, 24 januari 2004",
    asal: "Probolinggo",
  },
  {
    id: "73",
    nama: "Yefta Octavianus S",
    kelompok: "2",
    motto: "Penting semangat mawon",
    telepon: "085105120605",
    ttl: "Banyuwangi, 04 Oktober 2004",
    asal: "Banyuwangi",
  },
  {
    id: "74",
    nama: "Susilowati Syafa Adilah",
    kelompok: "2",
    motto: "Terus perbaiki diri, jangan sampai menyesal di lain hari",
    telepon: "082139240394",
    ttl: "Gresik, 20 September 2004",
    asal: "Gresik",
  },
  {
    id: "75",
    nama: "Abdullah Shamil Basayev",
    kelompok: "3",
    motto: "Tak akan ada yang berubah jika kau tak berubah",
    telepon: "081357717345",
    ttl: "Surabaya, 15 Maret 2005",
    asal: "Blitar",
  },
  {
    id: "76",
    nama: "AHMAD DZUL FADHLI HANNAN",
    kelompok: "3",
    motto: "Hidup untuk tujuan, bukan tujuan untuk hidup",
    telepon: "08819864174",
    ttl: "Nganjuk, 12 Juni 2004",
    asal: "Kec. Tanjunganom, Kab. Nganjuk",
  },
  {
    id: "77",
    nama: "Ahmad Rifqi Hendriansyah",
    kelompok: "3",
    motto: "jika orang lain bisa kenapa harus saya",
    telepon: "082334251796",
    ttl: "Situbondo, 22 September 2005",
    asal: "Situbondo",
  },
  {
    id: "78",
    nama: "Aryo Adi Putro",
    kelompok: "3",
    motto: "Jangan pernah bosan mempelajari hal baru",
    telepon: "085815346834",
    ttl: "Jember, 7 Juni 2004",
    asal: "Malang",
  },
  {
    id: "79",
    nama: "atabik mutawakil",
    kelompok: "3",
    motto: "hidup seperti larry",
    telepon: "087816025121",
    ttl: "tegal 31 march 2004",
    asal: "tegal",
  },
  {
    id: "80",
    nama: "Billy Maulana Ferdinan",
    kelompok: "3",
    motto:
      "Terus hidup menjadi apapun yang kamu inginkan walau dunia tak menginginkan itu",
    telepon: "085781555905",
    ttl: "Malang, 18 Juni 2003",
    asal: "Karangrejo Utara RT 14 RW 12",
  },
  {
    id: "81",
    nama: "Dahniar Davina",
    kelompok: "3",
    motto: "Masa depan adalah milik mereka yang percaya dengan impiannya",
    telepon: "081252749394",
    ttl: "Mojokerto, 09 Agustus 2004",
    asal: "Malang",
  },
  {
    id: "82",
    nama: "Dandi Azrul Syahputra",
    kelompok: "3",
    motto: "Hidup seperti larry",
    telepon: "085923419636",
    ttl: "Surabaya,22 Desember 2004",
    asal: "Malang",
  },
  {
    id: "83",
    nama: "Dinarul Lailil Mubarokah",
    kelompok: "3",
    motto: "ga ada yang sia-sia,jangan menyerah ayo coba lagi!",
    telepon: "081554873962",
    ttl: "Trenggalek,26 Agustus 2004",
    asal: "Kediri",
  },
  {
    id: "84",
    nama: "Fajar Aditya Nugraha",
    kelompok: "3",
    motto: "Dipaksa, terpaksa, terbiasa",
    telepon: "085232892944",
    ttl: "Kediri, 22 Agustus 2004",
    asal: "Kota Kediri",
  },
  {
    id: "85",
    nama: "Fakhira zahrany nardin",
    kelompok: "3",
    motto: "Never stop trying",
    telepon: "087760409688",
    ttl: "Malang 8 januari 2003",
    asal: "Jl.letjen s parman II no 18 malang",
  },
  {
    id: "86",
    nama: "Fallujah Ramadi Camshah",
    kelompok: "3",
    motto: "Lakukan hal yang ingin dilakukan",
    telepon: "085718040815",
    ttl: "Jakarta, 15 Januari 2004",
    asal: "Jakarta",
  },
  {
    id: "87",
    nama: "Fauziyyah Adelia Ramanda",
    kelompok: "3",
    motto: "tetap semangat dan jangan menyerah",
    telepon: "081217482341",
    ttl: "Yogyakarta 8 November 2004",
    asal: "Malang",
  },
  {
    id: "88",
    nama: "Ghetsa Ramadhani Riska Arryanti",
    kelompok: "3",
    motto: "Hiduplah apa adanya, bukan ada apanya",
    telepon: "085801546347",
    ttl: "Tuban, 22 Oktober 2005",
    asal: "Tuban",
  },
  {
    id: "89",
    nama: "Gilang Purnomo",
    kelompok: "3",
    motto: "Jangan hanya menunggu, tetapi ciptakan waktu anda sendiri.",
    telepon: "085706105114",
    ttl: "Kediri, 05 Mei 2005",
    asal: "Jln Sumber Bulus rt 06 rw 02 Kel Tosaren Kec Pesantren Kota Kediri",
  },
  {
    id: "90",
    nama: "Haikal Muhammad Rafli",
    kelompok: "3",
    motto: "time waits for no one",
    telepon: "082131940020",
    ttl: "Surabaya, 16 Januari 2005",
    asal: "Malang",
  },
  {
    id: "91",
    nama: "Haura Archia Sarapova Putri Kresna",
    kelompok: "3",
    motto: "Jangan sia siakan hidupmu karna hidup cuman sekali",
    telepon: "087861801231",
    ttl: "Pasuruan, 06 Maret 2005",
    asal: "Pasuruan",
  },
  {
    id: "92",
    nama: "Hizkia Elsadanta",
    kelompok: "3",
    motto: "Hidup seperti larry",
    telepon: "08978513995",
    ttl: "Batam, 26 Desember 2003",
    asal: "Batam",
  },
  {
    id: "93",
    nama: "Indi Warda Ramadhani",
    kelompok: "3",
    motto:
      "Betapapun sulitnya hidup, selalu ada sesuatu yang dapat Anda lakukan dan berhasil.",
    telepon: "085840864439",
    ttl: "Malang , 22 Oktober 2005",
    asal: "Malang",
  },
  {
    id: "94",
    nama: "Johnatan David Gersom",
    kelompok: "3",
    motto: "Semua hal itu Positif",
    telepon: "081234396929",
    ttl: "Sidoarjo 9 Juni 2005",
    asal: "Pandaan- paruruan",
  },
  {
    id: "95",
    nama: "Mochamad Zacky Yudha Ardiansyah",
    kelompok: "3",
    motto: "takdir tidak pernah salah alamat",
    telepon: "081252289379",
    ttl: "Malang 29 November 2004",
    asal: "Malang",
  },
  {
    id: "96",
    nama: "Mochammad Zidny Nesywan Kurniawan",
    kelompok: "3",
    motto: "we never know",
    telepon: "089613354354",
    ttl: "Malang, 07 Agustus 2005",
    asal: "Malang",
  },
  {
    id: "97",
    nama: "MUHAMMAD ABHINAYA ZURFA",
    kelompok: "3",
    motto: "BERSAMA NANANG, PASTI MENANG",
    telepon: "085338364410",
    ttl: "NGANJUK 22 FEBRUARI 2005",
    asal: "NGANJUK",
  },
  {
    id: "98",
    nama: "MUHAMMAD ATHO'ILLAH MU'THISYAH",
    kelompok: "3",
    motto: "antitesis",
    telepon: "085815205684",
    ttl: "Mojokerto, 21 mei 2005",
    asal: "Mojokerto",
  },
  {
    id: "99",
    nama: "Muhammad Nazril Nur Rahman",
    kelompok: "3",
    motto: "Hinaan adalah semangat",
    telepon: "085694342522",
    ttl: "Probolinggo, 15 September 2005",
    asal: "Probolinggo",
  },
  {
    id: "100",
    nama: "Muhammad Zaki",
    kelompok: "3",
    motto: "kita harus hidup lebih baik dari pada kemaren",
    telepon: "085954711445",
    ttl: "Pasuruan,13mei 2005",
    asal: "kota pasuruan",
  },
  {
    id: "101",
    nama: "Nabhan Rizqi Julian Saputro",
    kelompok: "3",
    motto: "Kalau yg lain bisa saya harus lebih bisa",
    telepon: "0895367117356",
    ttl: "Probolinggo, 19 Juli 2004",
    asal: "Probolinggo, Leces",
  },
  {
    id: "102",
    nama: "Nahdia Putri Safira",
    kelompok: "3",
    motto: "Berani ambil risiko, bermimpi besar, dan berharap besar.",
    telepon: "085607587100",
    ttl: "Malang, 18 Agustus 2005",
    asal: "Madiun",
  },
  {
    id: "103",
    nama: "Rahmalia Mutia Farda",
    kelompok: "3",
    motto: "muda berjuang, tua banyak uang hehe",
    telepon: "082141002043",
    ttl: "Jombang, 28 Januari 2005",
    asal: "Jombang",
  },
  {
    id: "104",
    nama: "RANDA HERU KUSUMA",
    kelompok: "3",
    motto: "hidup tanpa pengalaman sama dengan hidup tanpa uang",
    telepon: "081217451041",
    ttl: "PASURUAN, 30-08-2004",
    asal: "PASURUAN",
  },
  {
    id: "105",
    nama: "Reika Amalia S",
    kelompok: "3",
    motto: "tetaplah hidup untuk ibumu",
    telepon: "082140874629",
    ttl: "Ponorogo, 29 November 2005",
    asal: "Malang",
  },
  {
    id: "106",
    nama: "Revani Nanda Putri",
    kelompok: "3",
    motto: "Just Rise and Shine",
    telepon: "08883066316",
    ttl: "Jember, 16 Desember 2004",
    asal: "Kota Malang",
  },
  {
    id: "107",
    nama: "Salsabila Mahda Runisha",
    kelompok: "3",
    motto: "Less Is More",
    telepon: "081918242172",
    ttl: "Yeh Sumbul, 25 Februari 2005",
    asal: "Jembrana, Bali",
  },
  {
    id: "108",
    nama: "Sharlyf Shaquille Syani",
    kelompok: "3",
    motto: "Selalu berusaha dan jangan pernah menyerah",
    telepon: "?081553199699?",
    ttl: "Pasuruan,03-10-2005",
    asal: "kalimantan timur",
  },
  {
    id: "109",
    nama: "Tomi Martino Affandi",
    kelompok: "3",
    motto: "berusaha.",
    telepon: "085731853160",
    ttl: "Tulungagung, 23 Maret 2004",
    asal: "Blitar",
  },
  {
    id: "110",
    nama: "Zaki Muhammad Athallah Erlangga",
    kelompok: "3",
    motto: "Tindakan adalah jalan menuju kesuksesan",
    telepon: "082193807761",
    ttl: "Makassar 22 Januari 2005",
    asal: "Makassar",
  },
  {
    id: "111",
    nama: "Adani Salsabila",
    kelompok: "3",
    motto: "just keep swimming, just keep swimming",
    telepon: "085749339382",
    ttl: "Jombang, 14 Oktober 2004",
    asal: "Bangil",
  },
  {
    id: "112",
    nama: "Aaisyah Nursalsabiil Ni Patriarti",
    kelompok: "4",
    motto:
      "Gagal bukan berarti berakhir tapi gagal adalah salah satu dari tahapan menuju target sasaran",
    telepon: "081358848358",
    ttl: "Sidoarjo, 30 November 2003",
    asal: "Malang",
  },
  {
    id: "113",
    nama: "Adinda Ivanka Maysanda Putri",
    kelompok: "4",
    motto:
      "Hiduplah seakan kamu mati besok, belajarlah seakan kamu�hidup�selamanya.",
    telepon: "085854387620",
    ttl: "Batu, 3 Mei 2005",
    asal: "Batu",
  },
  {
    id: "114",
    nama: "Afrizal Qurratul Faizin",
    kelompok: "4",
    motto: "Jadilah bunga yang mekar di dalam hancurnya dunia",
    telepon: "087888974645",
    ttl: "Malang, 12 September 2005",
    asal: "Malang",
  },
  {
    id: "115",
    nama: "AGITA PUTRI SALSABILA AJI",
    kelompok: "4",
    motto: "Kreativitas membutuhkan keberanian untuk melepaskan kepastian",
    telepon: "085736837350",
    ttl: "Purworejo,3 April 2004",
    asal: "Kabupaten Malang",
  },
  {
    id: "116",
    nama: "Alvanza Saputra Yudha",
    kelompok: "4",
    motto: "Jalanin aja dulu",
    telepon: "0895360215603",
    ttl: "Malang, 08 Juli 2004",
    asal: "Malang",
  },
  {
    id: "117",
    nama: "An Naastasya Sakina",
    kelompok: "4",
    motto:
      "Kalo jatuh ya bangun lagi, pelan pelan saja tidak apa yang penting bangkit kembali",
    telepon: "085706592519",
    ttl: "Malang, 20 September 2003",
    asal: "Malang",
  },
  {
    id: "118",
    nama: "Atsilah Amany Putri Harsuma",
    kelompok: "4",
    motto: "sholat hemat bodoamat",
    telepon: "081359345579",
    ttl: "Pasuruan, 18 Oktober 2004",
    asal: "Bangil, Jawa Timur",
  },
  {
    id: "119",
    nama: "Azkiya Putri Ihtiarilah",
    kelompok: "4",
    motto: "Don't give up, happiness will come after your tiredness",
    telepon: "081217090683",
    ttl: "Jember, 20 Maret 2004",
    asal: "Jember",
  },
  {
    id: "120",
    nama: "Bagas Satria Yudho Nugraha",
    kelompok: "4",
    motto: "Selalu berusaha yang terbaik",
    telepon: "081342767403",
    ttl: "Nganjuk 08 Desember 2004",
    asal: "Malang",
  },
  {
    id: "121",
    nama: "Beryl Funky Mubarok",
    kelompok: "4",
    motto: "I have no enemies",
    telepon: "081456010040",
    ttl: "Tulungagung, 20 Juli 2023",
    asal: "Landungsari",
  },
  {
    id: "122",
    nama: "Devita Dwi Lestari",
    kelompok: "4",
    motto: "Hidup bahagia dunia akhirat",
    telepon: "081515912833",
    ttl: "Sidoarjo, 01 November 2004",
    asal: "Sidoarjo",
  },
  {
    id: "123",
    nama: "Dimas Arya Sadewa",
    kelompok: "4",
    motto: "Nikmati proses dan setiap perubahan yang terjadi di dalam hidup",
    telepon: "081703139494",
    ttl: "Ponorogo, 03-06-2004",
    asal: "Ponorogo",
  },
  {
    id: "124",
    nama: "Dimas Setyo Nugroho",
    kelompok: "4",
    motto:
      "Jika ingin merubah takdir, mulailah merubah diri menjadi lebih baik",
    telepon: "081252583741",
    ttl: "Tulungagung, 12 Agustus 2004",
    asal: "Tulungagung",
  },
  {
    id: "125",
    nama: "Dipa praja pramono",
    kelompok: "4",
    motto: "Tetap semangat menggapai cita-cita",
    telepon: "087725050445",
    ttl: "Magetan, 15 Oktober 2005",
    asal: "Malang",
  },
  {
    id: "126",
    nama: "Dzulfikar Muhammad Al Ghifari",
    kelompok: "4",
    motto: "Tetaplah baik walau keadaan tidak baik baik saja",
    telepon: "087866711494",
    ttl: "Malang, 5 April 2005",
    asal: "Kota Malang",
  },
  {
    id: "127",
    nama: "ERIKA ATTHACARYA PUTRI CAHYANI",
    kelompok: "4",
    motto: "tetap happy walau banyak rintangan",
    telepon: "0881036309124",
    ttl: "14 NOVEMBER 2004",
    asal: "BLITAR",
  },
  {
    id: "128",
    nama: "Farhan nur alifian",
    kelompok: "4",
    motto: "Dont never",
    telepon: "081228718504",
    ttl: "Pati, 6 september 2002",
    asal: "Pati, jawa tengah",
  },
  {
    id: "129",
    nama: "Galung Erlyan Tama",
    kelompok: "4",
    motto: "Dunia Sementara Akhirat Selamanya",
    telepon: "082334041140",
    ttl: "Ponorogo, 08 Maret 2005",
    asal: "Gegeran, Sukorejo, Ponorogo, Jatim",
  },
  {
    id: "130",
    nama: "Iga Ramadana Sahputra",
    kelompok: "4",
    motto: "Chase your dreams, create your own destiny",
    telepon: "085604657370",
    ttl: "Malang, 06 November 2003",
    asal: "Malang",
  },
  {
    id: "131",
    nama: "Ivansyah Eka Oktaviadi Santoso",
    kelompok: "4",
    motto:
      "Kemarin adalah kenangan, hari ini adalah kenyataan, hari esok adalah harapan",
    telepon: "085707092328",
    ttl: "Surabaya,4 Oktober 2004",
    asal: "Gresik",
  },
  {
    id: "132",
    nama: "Izzatir Rofi'ah",
    kelompok: "4",
    motto:
      "Jangan pernah takut akan kegagalan, Karena itu adalah cobaan menuju jalan kesuksesan.",
    telepon: "081359844557",
    ttl: "Gresik, 29 April 2005",
    asal: "Kec. Kesamben, Kab. Blitar",
  },
  {
    id: "133",
    nama: "Kartika Tri Juliana",
    kelompok: "4",
    motto:
      "jangan paksakan dirimu, karna yang tau usahamu hanyalah dirimu sendiri",
    telepon: "089516078334",
    ttl: "Malang, 15 Juli 2004",
    asal: "Malang",
  },
  {
    id: "134",
    nama: "Kevin Bramasta Arvyto Wardhana",
    kelompok: "4",
    motto: "Dreams can only be dream if you keep dreaming�about�it",
    telepon: "08113682704",
    ttl: "Malang, 27 April 2005",
    asal: "Malang",
  },
  {
    id: "135",
    nama: "Kibar Mustofa",
    kelompok: "4",
    motto:
      "Selalu menjadi orang yang tidak pernah berhenti untuk mencari tahu hal baru entah dari teknologi dan bidang lainnya",
    telepon: "085843657583",
    ttl: "Malang, 24 Mei 2004",
    asal: "Malang, klayatan III",
  },
  {
    id: "136",
    nama: "Lelyta Meyda Ayu Budiyanti",
    kelompok: "4",
    motto:
      "Pendidikan bukan tentang mengenai mengisi wadah yang kosong, tetapi pendidikan merupakan proses untuk menyalakan api pikiran.",
    telepon: "081252295353",
    ttl: "Tulungagung, 29 Mei 2004",
    asal: "Tulungagung",
  },
  {
    id: "137",
    nama: "Mikaila Kafka Akmalsyah",
    kelompok: "4",
    motto: "Manusiakanlah manusia",
    telepon: "081247884695",
    ttl: "Gresik,24 Juli 2004",
    asal: "Gresik",
  },
  {
    id: "138",
    nama: "Moh Farhan Adien Alfahrezy",
    kelompok: "4",
    motto: "Perjalanan seribu batu bermula dari satu langkah",
    telepon: "No telp",
    ttl: "13 Juni 2005",
    asal: "Malang",
  },
  {
    id: "139",
    nama: "Muhammad Al-Fatih Ulima Robby",
    kelompok: "4",
    motto: "rajin dan gigih dalam menghadapi kehidupan",
    telepon: "081359546301",
    ttl: "malang,27-06-2004",
    asal: "Batu",
  },
  {
    id: "140",
    nama: "Muhammad Rifqi Rizqullah",
    kelompok: "4",
    motto: "Muda berkelana, Tua bercerita",
    telepon: "081292202979",
    ttl: "Malang, 7 Oktober 2004",
    asal: "Malang, Jawa Timur",
  },
  {
    id: "141",
    nama: "Muhammad Rizal Al Baihaqi",
    kelompok: "4",
    motto: "Jadilah starboy",
    telepon: "087803295917",
    ttl: "Malang, 12 Juni 2004",
    asal: "Malang",
  },
  {
    id: "142",
    nama: "Patrik Satya Panitis Raharjo",
    kelompok: "4",
    motto: "Happy Happy ajalah, daripada stress terus",
    telepon: "081359314308",
    ttl: "Malang, 06 Oktober 2004",
    asal: "Malang Jawa Timur",
  },
  {
    id: "143",
    nama: "Rafa Fadil Aras",
    kelompok: "4",
    motto: "Just keep doing things you wanna do",
    telepon: "085850889729",
    ttl: "Malang, 5 Desember 2004",
    asal: "Malang",
  },
  {
    id: "144",
    nama: "Rocky Alessandro Kristanto",
    kelompok: "4",
    motto:
      "Sepahit apapun cobaannya, jalani saja karena hasil akhirnya pasti manis",
    telepon: "08819715943",
    ttl: "Kediri, 26 Juni 2005",
    asal: "Kediri",
  },
  {
    id: "145",
    nama: "SATRIA ERSA NARENDRA",
    kelompok: "4",
    motto: "Kita bisa karena terbiasa",
    telepon: "085731761342",
    ttl: "Malang, 12 Juni 2004",
    asal: "Kota Malang",
  },
  {
    id: "146",
    nama: "Satria Rakhmadani",
    kelompok: "4",
    motto:
      '"Tomorrow is a mystery, Yesterday is a history, and today is a gift"',
    telepon: "085335510121",
    ttl: "Gresik, 5 Mei 2005",
    asal: "Kota Malang, Jawa Timur",
  },
  {
    id: "147",
    nama: "Surya Rahmat Fatahillah",
    kelompok: "4",
    motto: "past in your mind, future in your hand",
    telepon: "085850630080",
    ttl: "Pasuruan , 16 Februari 2005",
    asal: "Bangil",
  },
  {
    id: "148",
    nama: "Textona Ardha Rilianta",
    kelompok: "4",
    motto: "Berhenti mengeluh dan mulai berubah",
    telepon: "081906424521",
    ttl: "Tulungagung, 28 September 2004",
    asal: "Tanjungsari, Boyolangu, Tulungagung, Jawa Timur",
  },
  {
    id: "149",
    nama: "Valentina Santi Grehasta",
    kelompok: "4",
    motto: "Tarik napas keberanian, hembuskan rasa takut",
    telepon: "081335114863",
    ttl: "Banyuwangi, 14 Februari 2004",
    asal: "Banyuwangi",
  },
  {
    id: "150",
    nama: "Yusra Yusuf",
    kelompok: "4",
    motto: "Jangan mau tuk mengalir atau kau akan hanyut dan hilang",
    telepon: "085785491800",
    ttl: "Blitar, 21 Juli 2004",
    asal: "Blitar, Jawa Timur",
  },
  {
    id: "151",
    nama: "Alexander agung raya",
    kelompok: "6",
    motto: "Jalani dulu hidup ini dengan semangat",
    telepon: "089676407163",
    ttl: "Banyuwangi, 21 oktober 2004",
    asal: "Banyuwangi",
  },
  {
    id: "152",
    nama: "Ananda Rahmawati",
    kelompok: "6",
    motto:
      '"Hiduplah seakan kamu mati besok, belajarlah seakan kamu hidup selamanya."',
    telepon: "087721164724",
    ttl: "Malang, 24 September 2005",
    asal: "Malang",
  },
  {
    id: "153",
    nama: "Aril Ibbet Ardana Putra",
    kelompok: "6",
    motto: "Jika yang lain bisa, kenap harus saya",
    telepon: "085156489059",
    ttl: "Banyuwangi, 24 November 2004",
    asal: "Banyuwangi",
  },
  {
    id: "154",
    nama: "Bagas Nusa Tama",
    kelompok: "6",
    motto: "Dengan pendidikan kamu bisa mengubah dunia",
    telepon: "083140743454",
    ttl: "Kebun Agung, 16 Agustus 2005",
    asal: "Pontianak",
  },
  {
    id: "155",
    nama: "Bayu Putra Laksmana",
    kelompok: "6",
    motto: "Menjadi kaya itu sebuah tujuan utama",
    telepon: "081318785024",
    ttl: "Malang, 03-04-2005",
    asal: "Malang",
  },
  {
    id: "156",
    nama: "DEVA SELVIANA",
    kelompok: "6",
    motto: "berbuat baiklah tanpa alasan",
    telepon: "085791357577",
    ttl: "KEDIRI, 28 DESEMBER 2004",
    asal: "KEDIRI",
  },
  {
    id: "157",
    nama: "DIMAS ADI BAYU SAMUDRA",
    kelompok: "6",
    motto: "Jika bisa kenapa tidak",
    telepon: "089613031465",
    ttl: "Malang, 17 desember 2004",
    asal: "Surabaya",
  },
  {
    id: "158",
    nama: "Dini Elminingtyas Rahayu Wilujeng",
    kelompok: "6",
    motto:
      "Tidak pernah menyerah, karena hidup bukan bergantung padamu, justru kamulah yang bergantung pada hidupmu.",
    telepon: "081358068566",
    ttl: "Batu, 28 Agustus 2005",
    asal: "Kota Batu",
  },
  {
    id: "159",
    nama: "Erfin Jauhari Dwi Brian",
    kelompok: "6",
    motto: "Put Your Vision To Reality",
    telepon: "081327537235",
    ttl: "Malang, 7 April 2005",
    asal: "Malang",
  },
  {
    id: "160",
    nama: "Fachry Akbar Bagaskara",
    kelompok: "6",
    motto:
      "Pedih dimatapun lihat baik baik, seberapa silaupun itulah masa depan kita",
    telepon: "081931522932",
    ttl: "Malang, 30 Agustus 2004",
    asal: "Pakisaji",
  },
  {
    id: "161",
    nama: "Fahri Zanuar Pradian",
    kelompok: "6",
    motto: "Tetap memilih yang dirumah di kala cewe maba menyerang",
    telepon: "085331631151",
    ttl: "Sumenep, 24 01 2005",
    asal: "Malang",
  },
  {
    id: "162",
    nama: "Farrel Augusta Dinata",
    kelompok: "6",
    motto: "Keep learning and keep improving",
    telepon: "085782214618",
    ttl: "Blitar, 13 Agustus 2005",
    asal: "Kabupaten Blitar",
  },
  {
    id: "163",
    nama: "HANIN MARIAM ABIYYAH HENDRIK",
    kelompok: "6",
    motto: "make better mistakes",
    telepon: "0895712540107",
    ttl: "Batam 06 juli 2005",
    asal: "Batam",
  },
  {
    id: "164",
    nama: "Isnaeny Tri Larassati",
    kelompok: "6",
    motto: "A negative mind will never give you a positive life",
    telepon: "085825195940",
    ttl: "Malang, 02 Juli 2004",
    asal: "Malang",
  },
  {
    id: "165",
    nama: "KEVIN ADIKA SAPUTRA",
    kelompok: "6",
    motto:
      "tetap hidup walau jadi parasit negara, se engganya jangan jadi parasit kehidupan diri sendiri",
    telepon: "0895347265465",
    ttl: "jombang 25-03-2004",
    asal: "jombang",
  },
  {
    id: "166",
    nama: "Luthfi Triaswangga",
    kelompok: "6",
    motto: "Tetaplah mekar seperti bunga walau sedang d tengahi medan perang",
    telepon: "08996331305",
    ttl: "Bekasi, 27 Februari 2005",
    asal: "Bogor",
  },
  {
    id: "167",
    nama: "M. Zidna Billah Faza",
    kelompok: "6",
    motto: "Darah ku biru soalnya mahasiswa Polinema",
    telepon: "085641337658",
    ttl: "Pekalongan, 27 Juni 2005",
    asal: "Kab. Batang",
  },
  {
    id: "168",
    nama: "Muhammad Erril Putra Pratidina",
    kelompok: "6",
    motto: "Kerjakan apa yang bisa dikerjakan",
    telepon: "082352047050",
    ttl: "Ponorogo, 20 April 2005",
    asal: "Ponorogo & Pontianak",
  },
  {
    id: "169",
    nama: "Muhammad Ircham daffansyah",
    kelompok: "6",
    motto: "Bekerja setinggi2nya untuk istirahat di rendah2nya",
    telepon: "082145343418",
    ttl: "Malang,20nov2005",
    asal: "Malang",
  },
  {
    id: "170",
    nama: "Muhammad Rifda Musyaffa'",
    kelompok: "6",
    motto: "Hiduplah setidaknya untuk janjimu",
    telepon: "081216718180",
    ttl: "Mojokerto 18 Mei 2004",
    asal: "Mojokerto",
  },
  {
    id: "171",
    nama: "Nathanael Juan Gracedo",
    kelompok: "6",
    motto: "Let It Flow!",
    telepon: "082233617475",
    ttl: "Kediri, 30 Juli 2004",
    asal: "Kediri",
  },
  {
    id: "172",
    nama: "Okan Syahdana",
    kelompok: "6",
    motto: "Strong (stres tak tertolong)",
    telepon: "082228353842",
    ttl: "Malang, 30 Mei 2005",
    asal: "Turen Kabupaten Malang",
  },
  {
    id: "173",
    nama: "Raihan Abdi Darmawan",
    kelompok: "6",
    motto: "Habiskan jatah sialmu, siapa tahu Tuhan akan merefillnya lagi",
    telepon: "085730488990",
    ttl: "Batu, 24 Januari 2005",
    asal: "Tulungagung",
  },
  {
    id: "174",
    nama: "Rensi Meila Yulvinata",
    kelompok: "6",
    motto: "try first and i will shine",
    telepon: "082131596693",
    ttl: "Kediri, 23 Mei 2004",
    asal: "Kediri",
  },
  {
    id: "175",
    nama: "Rizqi Bagus Andrean",
    kelompok: "6",
    motto: "Semangat Menggapai Impian",
    telepon: "085155060743",
    ttl: "Tulungagung, 27 Juni 2003",
    asal: "Tulungagung",
  },
  {
    id: "176",
    nama: "Sherly Lutfi Azkiah Sulistyawati",
    kelompok: "6",
    motto: "Lebih baik mencoba daripada tidak sama sekali.",
    telepon: "081358834080",
    ttl: "Malang, 24 Desember 2004",
    asal: "Malang",
  },
  {
    id: "177",
    nama: "Syifa Revalina Kamila",
    kelompok: "6",
    motto: "Tetaplah hidup",
    telepon: "085749543166",
    ttl: "Nganjuk, 19 februari 2005",
    asal: "Malang",
  },
  {
    id: "178",
    nama: "Tyara Kusuma Nevada",
    kelompok: "6",
    motto:
      "Selalu Berbuatlah baik, karena kita tidak tahu kebaikan mana yang akan menolong kita",
    telepon: "082142204984",
    ttl: "Malang, 11 Februari 2006",
    asal: "Malang",
  },
  {
    id: "179",
    nama: "Vanessa Cristin Natalia",
    kelompok: "6",
    motto: "kalo jatuh 7 kali, bangun 8 kali",
    telepon: "085812431350",
    ttl: "Malang, 14 Desember 2004",
    asal: "Malang",
  },
  {
    id: "180",
    nama: "VEMAS BAGUS FERMANDA",
    kelompok: "6",
    motto: "Berani ambil resiko",
    telepon: "085719040578",
    ttl: "KEDIRI,1 APRIL 2004",
    asal: "KEDIRI",
  },
  {
    id: "181",
    nama: "VERA EFITA HUDI PUTRI",
    kelompok: "6",
    motto: "Aku cinta diriku, aku bisa",
    telepon: "089626065619",
    ttl: "Tuban, 22 september204",
    asal: "TUBAN JATIM",
  },
  {
    id: "182",
    nama: "Wahyu Rizky Cahyana",
    kelompok: "6",
    motto: "Kau akan tahu",
    telepon: "087743711669",
    ttl: "Blitar, 16 Oktober 2004",
    asal: "Blitar",
  },
  {
    id: "183",
    nama: "YUMA AKHUNZA KAUSAR PUTRA",
    kelompok: "6",
    motto: "kita punya rencana tapi tuhan yang menentukan",
    telepon: "081217187647",
    ttl: "Kediri,18 Sepetember 2003",
    asal: "Kota Madiun",
  },
  {
    id: "184",
    nama: "Amelia Dhea Citra Karina",
    kelompok: "10",
    motto: "Kegagalan adalah awal dari kesuksesan",
    telepon: "0895383294110",
    ttl: "Kediri, 10 Oktober 2004",
    asal: "Kediri",
  },
  {
    id: "185",
    nama: "ARDHIO FATRA REVANGGA",
    kelompok: "10",
    motto: "Tetap semangat walau tidak ada penyemangat",
    telepon: "085856209302",
    ttl: "Blitar, 29 November 2004",
    asal: "Blitar",
  },
  {
    id: "186",
    nama: "Axelo Matthew Terang Barus",
    kelompok: "10",
    motto: "Jadilah diri sendiri dan jangan menyerah",
    telepon: "089680961924",
    ttl: "Surabaya, 5 April 2005",
    asal: "Kota Batu",
  },
  {
    id: "187",
    nama: "BOBY ROZAK SAPUTRA",
    kelompok: "10",
    motto: "bahagia",
    telepon: "0895605864920",
    ttl: "Tuban 06-04-2004",
    asal: "Tuban, Jawa Timur",
  },
  {
    id: "188",
    nama: "Damar Galih",
    kelompok: "10",
    motto: "Bernafas adalah keharusan",
    telepon: "081252031323",
    ttl: "Malang,22-12-2002",
    asal: "Lawang",
  },
  {
    id: "189",
    nama: "Danendra Nayaka Passadhi",
    kelompok: "10",
    motto: "Usaha dulu, hasil pikir belakangan",
    telepon: "085713788055",
    ttl: "Malang, 11 Oktober 2004",
    asal: "Malang, Jatim",
  },
  {
    id: "190",
    nama: "Deanissa Sherly Sabilla",
    kelompok: "10",
    motto: "Action is the key to success.",
    telepon: "083111076149",
    ttl: "Malang, 25 Agustus 2005",
    asal: "Malang",
  },
  {
    id: "191",
    nama: "Dhevina Agustina",
    kelompok: "10",
    motto: "Berusahalah mati matian untuk kesuksesan masa depan",
    telepon: "085655002441",
    ttl: "Malang, 25 Agustus 2004",
    asal: "Malang, 25 Agustus 2004",
  },
  {
    id: "192",
    nama: "Dika Arie Arrifky",
    kelompok: "10",
    motto: "Jangan menyerah tetap semangat",
    telepon: "082229819495",
    ttl: "Malang, 22 Januari 2005",
    asal: "Malang",
  },
  {
    id: "193",
    nama: "DINA RAHMAWATI",
    kelompok: "10",
    motto: "Diamku lebih berarti daripada kata-kata yang tak bermakna.",
    telepon: "087754153063",
    ttl: "Malang, 28 april 2004",
    asal: "Malang",
  },
  {
    id: "194",
    nama: "Dio Andika Pradana Mulia Tama",
    kelompok: "10",
    motto: "Tetapkan tujuan dalam hidupmu niscaya hidupmu tidak akan sia-sia",
    telepon: "085704024108",
    ttl: "Malang, 26 Maret 2004",
    asal: "Malang",
  },
  {
    id: "195",
    nama: "Eka Putri Natalya Kabelen",
    kelompok: "10",
    motto: "Believe in your self and find happiness in smalls things",
    telepon: "085232021239",
    ttl: "Nganjuk, 25 Desember 2004",
    asal: "Nganjuk",
  },
  {
    id: "196",
    nama: "Faiza Anathasya Eka Falen",
    kelompok: "10",
    motto: "Semuanya lucu, selama itu terjadi�pada�orang�lain",
    telepon: "081230948205",
    ttl: "Malang, 06 Agustus 2005",
    asal: "Malang, Jawa Timur",
  },
  {
    id: "197",
    nama: "fasya dita nasahah",
    kelompok: "10",
    motto: "kujalani hidup walaupun sambat",
    telepon: "087782169276",
    ttl: "malang,14 februari 2004",
    asal: "malang",
  },
  {
    id: "198",
    nama: "FAUZIE IKHLASUL AMNUR",
    kelompok: "10",
    motto: "TETAP SEMANGAT MESKIPUN TAK SESUAI EKSPETASI",
    telepon: "082141787716",
    ttl: "BANYUWANGI, 25 MARET 2005",
    asal: "BANYUWANGI",
  },
  {
    id: "199",
    nama: "Febrian Arka Samudra",
    kelompok: "10",
    motto: "Kesuksesan datang dari orang yang mau mencoba",
    telepon: "082257071031",
    ttl: "Malang, 24 Februari 2005",
    asal: "Malang, Jatim",
  },
  {
    id: "200",
    nama: "GEGAS ANUGRAH DERAJAT",
    kelompok: "10",
    motto: "YANG PENTING SHOLAT",
    telepon: "081231808302",
    ttl: "13 OKTOBER 2004",
    asal: "NGORO",
  },
  {
    id: "201",
    nama: "Gerly Vaeyungfan",
    kelompok: "10",
    motto: "I can, if I want",
    telepon: "085604054712",
    ttl: "Malang, 7 Oktober 2005",
    asal: "Malang",
  },
  {
    id: "202",
    nama: "Ghaisan Rafa Pradipta",
    kelompok: "10",
    motto: "Jadilah apa yang kita mau bukan yang orang mau",
    telepon: "0818538005",
    ttl: "Malang,18-juli-2005",
    asal: "Malang Lowokwaru",
  },
  {
    id: "203",
    nama: "Irsa Cahaya Widodo",
    kelompok: "10",
    motto:
      '"Yakin kepada diri sendiri dan Tuhan adalah cara agar impian dapat tercapai"',
    telepon: "085646628992",
    ttl: "Malang, 17 Maret 2005",
    asal: "Lumbangsari, Kec. Bululawang, Kab. Malang",
  },
  {
    id: "204",
    nama: "Ismi Atika",
    kelompok: "10",
    motto: "Fokus pada tujuan, bukan hambatan",
    telepon: "085259638605",
    ttl: "Sumenep, 26 Juni 2005",
    asal: "Madura Kangean",
  },
  {
    id: "205",
    nama: "Kanaya Abdielaramadhani Hidayat",
    kelompok: "10",
    motto:
      "Tuntutlah ilmu setinggi tinggi nya, karena kelak apa yang sudah kita tanam itu lah yang kita tuai",
    telepon: "081809460175?",
    ttl: "Mataram, 11 November 2005",
    asal: "Malang",
  },
  {
    id: "206",
    nama: "KARINA IKA INDASA",
    kelompok: "10",
    motto: "HARI INI BERJUANG HARI ESOK BER UANG",
    telepon: "082250042722",
    ttl: "Probolinggo, 17 Juni 2004",
    asal: "Probolinggo",
  },
  {
    id: "207",
    nama: "Leon Shan Yoedha Adjie",
    kelompok: "10",
    motto: "Sesungguhnya Allah bersama orang-orang yang sabar",
    telepon: "085175379090",
    ttl: "Sidoarjo, 13 Agustus 2004",
    asal: "Sidoarjo",
  },
  {
    id: "208",
    nama: "M Zuffar Rasendriya S",
    kelompok: "10",
    motto:
      'Jangan jadi orang lain agar orang" suka padamu, cukup jadilah dirimu sendiri saja',
    telepon: "081333561923",
    ttl: "Batu,1 Agustus 2005",
    asal: "Kota Batu",
  },
  {
    id: "209",
    nama: "Mochammad Audric Andhika Hidayatulloh",
    kelompok: "10",
    motto: "Be Yourself",
    telepon: "085812121478",
    ttl: "Mojokerto, 9 April 2005",
    asal: "Mojokerto",
  },
  {
    id: "210",
    nama: "Muhamad Syaifullah",
    kelompok: "10",
    motto: "Hidup sesuai budget",
    telepon: "085732776808",
    ttl: "Blitar 22 November 2004",
    asal: "Sukorejo,Udanawu,Blitar",
  },
  {
    id: "211",
    nama: "Muhammad Mahdi Arielreza Hafiz",
    kelompok: "10",
    motto:
      "sometimes u need to know that there�s thing u can and cannot control.",
    telepon: "085157571328",
    ttl: "JAKARTA, 09 Maret 2005",
    asal: "Bekasi",
  },
  {
    id: "212",
    nama: "Muhammad Naufal Pratomo",
    kelompok: "10",
    motto: "motivasi tanpa aksi hanyalah imajinasi",
    telepon: "087887561121",
    ttl: "Malang, 27 November 2004",
    asal: "Jakarta",
  },
  {
    id: "213",
    nama: "Muhammad Rohman Al Kautsar",
    kelompok: "10",
    motto: "Sembarang pokok OK",
    telepon: "087856432962",
    ttl: "Malang, 11 September 2004",
    asal: "Malang",
  },
  {
    id: "214",
    nama: "Nadia Pramudita",
    kelompok: "10",
    motto:
      "Everything happens for a reason, everything is to teach you a lesson",
    telepon: "085784195807",
    ttl: "Batu, 14 Juni 2004",
    asal: "Kota Batu",
  },
  {
    id: "215",
    nama: "Nurwahib Zakki Yahya",
    kelompok: "10",
    motto: "Selalu berusaha",
    telepon: "085106355699",
    ttl: "Madiun, 12 Juni 2005",
    asal: "Madiun",
  },
  {
    id: "216",
    nama: "Octrian Adiluhung Tito Putra",
    kelompok: "10",
    motto: "Tindakan adalah kunci menuju kesuksesan",
    telepon: "085771220364",
    ttl: "Probolinggo, 05 Oktober 2004",
    asal: "Probolinggo",
  },
  {
    id: "217",
    nama: "Ramadhan Maulana A",
    kelompok: "10",
    motto: "dijalanin aja sebisanya,kalo gabisa yauda gapapa",
    telepon: "085648275712",
    ttl: "Malang-11-November-2004",
    asal: "Malang",
  },
  {
    id: "218",
    nama: "Rasendriya Dafa Setiadi",
    kelompok: "10",
    motto: "tetap semangat walau agak anu",
    telepon: "085608016354",
    ttl: "malang 25 mei 2005",
    asal: "malang",
  },
  {
    id: "219",
    nama: "sadiya maritza",
    kelompok: "10",
    motto:
      "alani segala sesuatu dengan ikhlas, karena pasti ada hal besar menanti",
    telepon: "089681010691",
    ttl: "blitar, 8 sep 2004",
    asal: "blitar",
  },
  {
    id: "220",
    nama: "Sirfaratih",
    kelompok: "10",
    motto:
      "Terus berjalan,Bergerak tak harus lari kencang Cukup berjalan perlahan sebab selagi terus berjalan kita punya peluang untuk sampai tujuan.",
    telepon: "083841750041",
    ttl: "Pasuruan,24 Juni 2005",
    asal: "Pasuruan",
  },
  {
    id: "221",
    nama: "Erwan Majid",
    kelompok: "11",
    motto: "Jangan patah semangat",
    telepon: "081359377563",
    ttl: "Malang, 01 September 2004",
    asal: "Malang",
  },
  {
    id: "222",
    nama: "Adham Baskara",
    kelompok: "11",
    motto: "Pilihan tersulit membutuhkan tekad terkuat",
    telepon: "083845301791",
    ttl: "Pacitan, 31 Mei 2005",
    asal: "Jl. Kembang Kertas No.9, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141",
  },
  {
    id: "223",
    nama: "Aditya Yuhanda Putra",
    kelompok: "11",
    motto: "Langkah awal kesuksesan adalah mencoba",
    telepon: "089606775727",
    ttl: "Jakarta, 30 Januari 2004",
    asal: "Jakarta",
  },
  {
    id: "224",
    nama: "Agna Putra Prawira",
    kelompok: "11",
    motto: "sholat lah tepat waktu",
    telepon: "08515691728q",
    ttl: "Probolinggo, 13 Oktober 2004",
    asal: "Kota Probolinggo",
  },
  {
    id: "225",
    nama: "Alvi Choirinnikmah",
    kelompok: "11",
    motto: "Never Give up",
    telepon: "085851944299",
    ttl: "Blitar, 09 September 2004",
    asal: "Blitar",
  },
  {
    id: "226",
    nama: "Alya Ajeng Ayu",
    kelompok: "11",
    motto: "Hidup tak harus berlari, berjalan sudah cukup asal bisa sampai",
    telepon: "0895393583532",
    ttl: "Malang, 18 November 2004",
    asal: "Malang",
  },
  {
    id: "227",
    nama: "Aryan Saputra Rahmad",
    kelompok: "11",
    motto: "Makkah, Madinah, Manchester",
    telepon: "081276210929",
    ttl: "Bojonegoro,13 April 2004",
    asal: "Bojonegoro",
  },
  {
    id: "228",
    nama: "BELQIS IVANA FIDELIA ARFANY",
    kelompok: "11",
    motto: "Berani ambil risiko, bermimpi besar, dan berharap besar",
    telepon: "082140752116",
    ttl: "BLITAR, 30 DESEMBER 2004",
    asal: "BLITAR",
  },
  {
    id: "229",
    nama: "Duta Kurnia Ardhani",
    kelompok: "11",
    motto: "Habiskan jatah kalahmu",
    telepon: "087859882508",
    ttl: "Malang, 29 April 2005",
    asal: "Malang",
  },
  {
    id: "230",
    nama: "Dwi Ahmad Khairy",
    kelompok: "11",
    motto:
      "hidup itu komedi, klo ga bikin ketawa, mungkin jokes nya lagi garing aja",
    telepon: "082363838049",
    ttl: "Medan, 7 Juli 2005",
    asal: "Medan",
  },
  {
    id: "231",
    nama: "Esa Pratama Putri",
    kelompok: "11",
    motto: "Be yourself",
    telepon: "085706787548",
    ttl: "Blitar, 14 Juni 2004",
    asal: "Blitar",
  },
  {
    id: "232",
    nama: "FAREL MARYAM LAILA HAJIRI",
    kelompok: "11",
    motto: "Tetaplah hidup apapun yang terjadi",
    telepon: "085394786878",
    ttl: "Makassar,02 september 2005",
    asal: "Makassar",
  },
  {
    id: "233",
    nama: "Farrel Muchammad Kafie",
    kelompok: "11",
    motto: "Lakukan apapun yang ingin kamu lakukan",
    telepon: "085230994119",
    ttl: "Malang, 07 Desember 2004",
    asal: "Malang",
  },
  {
    id: "234",
    nama: "Fatima Sitta Maulidia",
    kelompok: "11",
    motto: "find joy in the little things",
    telepon: "085156388520",
    ttl: "Malang, 11 Desember 2004",
    asal: "Malang",
  },
  {
    id: "235",
    nama: "Fitri cahyaniati",
    kelompok: "11",
    motto: "Maju kedepan, terobos hambatan",
    telepon: "081240244083",
    ttl: "Wanenetat, 01 April 2005",
    asal: "Maluku",
  },
  {
    id: "236",
    nama: "FRANSISKA WIDYA KRISANTI",
    kelompok: "11",
    motto:
      "Jadikan kegagalan adalah pelajaran dan jadikan keberhasilan adalah kunci hidup",
    telepon: "082138069699",
    ttl: "Malang, 17 Desember 2004",
    asal: "Kota Malang",
  },
  {
    id: "237",
    nama: "Hayyin",
    kelompok: "11",
    motto: "Tidurlah lalu bermimpi, karena mimpi adalah kunci",
    telepon: "081333537649",
    ttl: "Sidoarjo, 26 Oktober 2004",
    asal: "Gempol Pasuruan",
  },
  {
    id: "238",
    nama: "Imel Theresia br Sembiring",
    kelompok: "11",
    motto: "Be yourself",
    telepon: "082277657532",
    ttl: "Kabanjahe 16 November 2005",
    asal: "Medan",
  },
  {
    id: "239",
    nama: "Keisya Nisrina Aulia",
    kelompok: "11",
    motto: "Dimanapun kamu ditempatkan oleh tuhan, itu yang terbaik untuk mu",
    telepon: "081331179534",
    ttl: "Banyuwangi, 03 April 2004",
    asal: "Banyuwangi",
  },
  {
    id: "240",
    nama: "Key Firdausi Alfarel",
    kelompok: "11",
    motto: "Berani karena benar takut karena salah",
    telepon: "081547318665",
    ttl: "Blitar 29 Maret 2023",
    asal: "Blitar",
  },
  {
    id: "241",
    nama: "Krisna Prawira Nugraha",
    kelompok: "11",
    motto: "Whether it's in vain or not, there is a meaning in every action",
    telepon: "081615045218",
    ttl: "Malang, 21 November 2005",
    asal: "Malang, Jawa Timur",
  },
  {
    id: "242",
    nama: "Luqman Ananta Abdul Hakim",
    kelompok: "11",
    motto:
      'Hidup adalah anugerah, syukurilah, jalanilah, nikmatilah, dan isilah hidup ini dgn sesuatu yg bermanfaat. Tetap semangat walaupun hidup ini "gini amat".',
    telepon: "08990337151",
    ttl: "Malang, 7 April 2005",
    asal: "Kepanjen, Kab. Malang",
  },
  {
    id: "243",
    nama: "M. Fatih Al Ghifary",
    kelompok: "11",
    motto: "yauda semangat",
    telepon: "082131536207",
    ttl: "Malang, 18 Maret 2005",
    asal: "Malang",
  },
  {
    id: "244",
    nama: "moch alfin burhanudin alqodri",
    kelompok: "11",
    motto: "tetap fokus pada tujuan, bukan hambatan",
    telepon: "081334770800",
    ttl: "probolinggo, 10 november 2004",
    asal: "probolinggo",
  },
  {
    id: "245",
    nama: "mohammad syifa'ul faj ismunir",
    kelompok: "11",
    motto: "jadilah pelangi untuk hujan orang lain",
    telepon: "085746909733",
    ttl: "malang, 6 desember 2004",
    asal: "malang",
  },
  {
    id: "246",
    nama: "Muchammad Nabil Haykal Widarto",
    kelompok: "11",
    motto: "Kadang Sesat, Kadang Tobat",
    telepon: "085108636167",
    ttl: "Malang, 22 Maret 2004",
    asal: "Malang",
  },
  {
    id: "247",
    nama: "Muhammad Kemal Syahru Ramadhan",
    kelompok: "11",
    motto: "Berkembang",
    telepon: "088803060931",
    ttl: "Surabaya, 01-11-2003",
    asal: "Sidoarjo",
  },
  {
    id: "248",
    nama: "Muhammad Naafi'ul Razzaq Witjaksono",
    kelompok: "11",
    motto: "Serakah saat berusaha, bersyukur saat mendapatkan hasil",
    telepon: "082257320226",
    ttl: "24 november 2004",
    asal: "Sidoarjo",
  },
  {
    id: "249",
    nama: "Nakita Gayuh Cakrawala",
    kelompok: "11",
    motto: "Kalo orang lain bisa kenapa saya tidak",
    telepon: "085890225502",
    ttl: "Malang 29 Maret 2004",
    asal: "Malang",
  },
  {
    id: "250",
    nama: "Nervalina Adzra Nora Aqilla",
    kelompok: "11",
    motto: "Start each day with a grateful heart",
    telepon: "081357971553",
    ttl: "Mojokerto, 30 Oktober 2004",
    asal: "Tuban",
  },
  {
    id: "251",
    nama: "Queenadhynar Azarine",
    kelompok: "11",
    motto:
      '"Jangan pernah menyerah pada apa yang benar-benar ingin kamu lakukan. Orang dengan mimpi besar lebih kuat daripada orang dengan semua fakta."',
    telepon: "081238285591",
    ttl: "Probolinggo, 09 September 2004",
    asal: "Probolinggo",
  },
  {
    id: "252",
    nama: "Rafi Abiyyu Airlangga",
    kelompok: "11",
    motto: "Fokus pada tujuan, bukan hambatan.",
    telepon: "082143494259",
    ttl: "Malang, 13 Juni 2005",
    asal: "Malang",
  },
  {
    id: "253",
    nama: "Rakai Seto Sembodo",
    kelompok: "11",
    motto: "if you see me fight with a bear, pray for the bear",
    telepon: "081513446664",
    ttl: "Jakarta, 29 Mei 2005",
    asal: "Jakarta",
  },
  {
    id: "254",
    nama: "Ramadhani Bi Hayyin",
    kelompok: "11",
    motto: "Tidurlah lalu bermimpi, karena mimpi adalah kunci",
    telepon: "081333537649",
    ttl: "Sidoarjo, 26 Oktober 2004",
    asal: "Gempol Pasuruan",
  },
  {
    id: "255",
    nama: "Rizkya Salsabila",
    kelompok: "11",
    motto: "Jika orang lain bisa, saya juga bisa.",
    telepon: "085742217624",
    ttl: "Pasuruan, 06 Juni 2004",
    asal: "Pasuruan",
  },
  {
    id: "256",
    nama: "Rizqi Fauzan",
    kelompok: "11",
    motto: 'uang se"Alef Null"pun tak berharga dihadapan hari esok',
    telepon: "089518952175",
    ttl: "11 mei 2005",
    asal: "Malang",
  },
  {
    id: "257",
    nama: "Romy Mahardika Pangestu Lazuardi",
    kelompok: "11",
    motto: "Hidup sudah susah nggak perlu ditambah susah lagi.",
    telepon: "081216369646",
    ttl: "Tulungagung, 17 Juni 2004",
    asal: "Jawa Timur",
  },
  {
    id: "258",
    nama: "SAFRIZAL RAHMAN",
    kelompok: "11",
    motto: "Jaya selalu",
    telepon: "082213286139",
    ttl: "Safrizal Rahman",
    asal: "Gadang",
  },
  {
    id: "259",
    nama: "Safrizal Rahman",
    kelompok: "11",
    motto: "Berguna Bagi semua",
    telepon: "082213286139",
    ttl: "Safrizal",
    asal: "Pasuruan Bangil",
  },
  {
    id: "260",
    nama: "SATRIO WISNU ADI PRATAMA",
    kelompok: "11",
    motto: "Jujur, berani, bertanggung jawab",
    telepon: "089520214500",
    ttl: "Malang 29 November 2004",
    asal: "Malang",
  },
  {
    id: "261",
    nama: "Syaqira Nazaretna",
    kelompok: "11",
    motto: "Berusaha tidak merepotkan orang lain",
    telepon: "085230208120",
    ttl: "Tulungagung, 30 Agustuus 2004",
    asal: "Tulungagung",
  },
  {
    id: "262",
    nama: "Affansyah Hanan Windharto",
    kelompok: "12",
    motto:
      "Kalah, tersesat atau lupa bukan berarti tidak bisa menjalani hidup dengan benar",
    telepon: "081235897747",
    ttl: "Lamongan, 23 September 2004",
    asal: "Lamongan",
  },
  {
    id: "263",
    nama: "Antonius Kaharap Kautsar",
    kelompok: "12",
    motto: "If I have to fight for my happiness then everyone must too",
    telepon: "081522841528",
    ttl: "Murung Raya, 11-08-2005",
    asal: "Kalimantang Tengah, Palangkaraya",
  },
  {
    id: "264",
    nama: "Aprilia Putri Anggraeni",
    kelompok: "12",
    motto: "Fokus pada tujuan,bukan hambatan",
    telepon: "085755742091",
    ttl: "Pasuruan,22 April 2005",
    asal: "Pasuruan",
  },
  {
    id: "265",
    nama: "Asmaul Rizwan",
    kelompok: "12",
    motto: "Nabung setengah mati, habisinnya setengah sadar",
    telepon: "085934461897",
    ttl: "Blitar, 4 Mei 2004",
    asal: "Blitar",
  },
  {
    id: "266",
    nama: "Aurelia Sekar Ellyansyah",
    kelompok: "12",
    motto: "Apapun masalah nya nangis solusinya",
    telepon: "081357039876",
    ttl: "Malang, 3 Juli 2005",
    asal: "Malang",
  },
  {
    id: "267",
    nama: "Baskoro Seno Aji",
    kelompok: "12",
    motto: "idealisme iblis dengan sayap yang merangkul semua orang",
    telepon: "081217177528",
    ttl: "Malang, 12 Desember 2004",
    asal: "Malang",
  },
  {
    id: "268",
    nama: "Danica Nasywa Putriniar",
    kelompok: "12",
    motto: "berjalanlah sesuai tempomu",
    telepon: "085104640640",
    ttl: "Malang, 8 November 2004",
    asal: "Malang",
  },
  {
    id: "269",
    nama: "Desi Karmila",
    kelompok: "12",
    motto: "Jangan sia-siakan kesempatan",
    telepon: "082134082846",
    ttl: "Pati, 31 Oktober 2004",
    asal: "Pati, Jawa Tengah",
  },
  {
    id: "270",
    nama: "Diajeng Sekar Arum",
    kelompok: "12",
    motto: "Akan ku hadapi semuanya meskipun dengan nangis sedikit",
    telepon: "087851944523",
    ttl: "Sidoarjo, 4 Juli 2004",
    asal: "Pasuruan",
  },
  {
    id: "271",
    nama: "Febriansyah adi nugroho",
    kelompok: "12",
    motto: "Mimpi di mulai hari ini bukan besok",
    telepon: "089635596818",
    ttl: "Malang 10 februari 2004",
    asal: "Malang",
  },
  {
    id: "272",
    nama: "Fiera Ziadattun Nisa'",
    kelompok: "12",
    motto: "kita bisa karena terbiasa",
    telepon: "085850211159",
    ttl: "Pasuruan, 07 januari 2005",
    asal: "Malang",
  },
  {
    id: "273",
    nama: "Golden Christian Gondo",
    kelompok: "12",
    motto: "Gagal yang sesungguhnya adalah berhenti untuk mencoba",
    telepon: "08999020805",
    ttl: "Bojonegoro, 2 Agustus 2005",
    asal: "Bojonegoro",
  },
  {
    id: "274",
    nama: "Hanif Faishal Hilmi",
    kelompok: "12",
    motto: "You only get one shot do not miss your chance to blow",
    telepon: "082135605818",
    ttl: "Pati, 11 Mei 2005",
    asal: "Pati",
  },
  {
    id: "275",
    nama: "Keysha Arindra Fabian",
    kelompok: "12",
    motto: "play hard, study hard, istira hard",
    telepon: "085856232904",
    ttl: "Pasuruan, 29 Agustus 2004",
    asal: "Pasuruan",
  },
  {
    id: "276",
    nama: "Khoirotun Nisa'",
    kelompok: "12",
    motto: "bersusah susah dahulu, santai kemudian",
    telepon: "0895620135270",
    ttl: "Malang, 25 Juli 2004",
    asal: "Malang",
  },
  {
    id: "277",
    nama: "M. Firmansyah",
    kelompok: "12",
    motto: "Jalanin aja dulu",
    telepon: "08986099537",
    ttl: "Kediri, 28 oktober 2004",
    asal: "Kediri",
  },
  {
    id: "278",
    nama: "Maharani Wirawan",
    kelompok: "12",
    motto: "gapailah cita-cita mu setinggi langit sampai menabrak satelit",
    telepon: "081233180171",
    ttl: "Pacitan, 02 Maret 2006",
    asal: "Pacitan",
  },
  {
    id: "279",
    nama: "Maisya Dhia N.A",
    kelompok: "12",
    motto: "Fake it till u make it",
    telepon: "089523791323",
    ttl: "Nganjuk,05 April 2005",
    asal: "Nganjuk",
  },
  {
    id: "280",
    nama: "Muhammad Adityo Rahman",
    kelompok: "12",
    motto: "Tidak ada keberanian tanpa rasa takut",
    telepon: "081334654388",
    ttl: "Malang, 01 Februari 2005",
    asal: "Malang",
  },
  {
    id: "281",
    nama: "Muhammad Ammar Hafizh",
    kelompok: "12",
    motto: "Berani ambil risiko",
    telepon: "082111596124",
    ttl: "Jakarta, 24 Maret 2004",
    asal: "Bogor",
  },
  {
    id: "282",
    nama: "Muhammad Dhia Ramadhanil Haq",
    kelompok: "12",
    motto: "Hadapi masalah dengan hahahihi..",
    telepon: "085767310173",
    ttl: "Padang,18 Oktober 2004",
    asal: "Padang,Sumatera Barat",
  },
  {
    id: "283",
    nama: "Muhammad Faruq Burhanudin Nahari",
    kelompok: "12",
    motto: "motto : kalo ada cobaan cobain dulu aja",
    telepon: "091233479829",
    ttl: "malang 07 februari 2005",
    asal: "malang",
  },
  {
    id: "284",
    nama: "Niriza Lailaumi Hidayat",
    kelompok: "12",
    motto: "gagal yang sesungguhnya adalah berhenti untuk mencoba",
    telepon: "085717865338",
    ttl: "Denpasar, 22 Desember 2005",
    asal: "Malang",
  },
  {
    id: "285",
    nama: "Nur Ayu Lailatul Azizah",
    kelompok: "12",
    motto: "Fokus pada tujuan, bukan hambatan",
    telepon: "085646190641",
    ttl: "Blitar, 27 Maret",
    asal: "Blitar",
  },
  {
    id: "286",
    nama: "Oktavian Eka Ramadhan",
    kelompok: "12",
    motto: "Tetap semangat, Jangan menyerah",
    telepon: "088235797087",
    ttl: "Batu, 19 Oktober 2004",
    asal: "Batu",
  },
  {
    id: "287",
    nama: "Pandya Cahya",
    kelompok: "12",
    motto: "Jalani apa yg kamu sukai",
    telepon: "082334762525",
    ttl: "Probolinggo, 20 Maret 2005",
    asal: "Probolinggo",
  },
  {
    id: "288",
    nama: "Pramudya Surya Anggara Putra",
    kelompok: "12",
    motto: "Ada duid ada kuasa",
    telepon: "085236736604",
    ttl: "Malang, 23 April 2004",
    asal: "Malang",
  },
  {
    id: "289",
    nama: "Safiro Alfarisi Haraya",
    kelompok: "12",
    motto: "Semua pasti ada jalannya",
    telepon: "08983484850",
    ttl: "Malang, 21 Maret 2005",
    asal: "Malang",
  },
  {
    id: "290",
    nama: "Satria Wiguna",
    kelompok: "12",
    motto: "jalanin aja , meskipun nangis dikit",
    telepon: "085100680080",
    ttl: "malang 22 februari 2005",
    asal: "Batu",
  },
  {
    id: "291",
    nama: "Satriya Viar Citta Purnama",
    kelompok: "12",
    motto: "Percoyo Tuhan",
    telepon: "089518952186",
    ttl: "Malang 11 Juni 2005",
    asal: "Malang",
  },
  {
    id: "292",
    nama: "Septian Tito Hidayahtullah",
    kelompok: "12",
    motto: "Hiduplah seakan kamu mati besok",
    telepon: "085746120214",
    ttl: "Probolinggo, 18 September 2005",
    asal: "Probolinggo",
  },
  {
    id: "293",
    nama: "STEVAN ZAKY SETYANTO",
    kelompok: "12",
    motto: "SUKSES, MEMBANGGAKAN DAN MEMBAHAGIAKAN ORANG TUA",
    telepon: "082229163261",
    ttl: "BLITAR, 1 SEPTEMBER 2004",
    asal: "SUMBERPUCUNG, MALANG",
  },
  {
    id: "294",
    nama: "titania aurellia putri dwiendra",
    kelompok: "12",
    motto: "tetep dijalanin sambil nangis dikit",
    telepon: "081292289327",
    ttl: "malang, 21 maret 2005",
    asal: "malang",
  },
  {
    id: "295",
    nama: "XAVIER ZAIDANE ATHAYA",
    kelompok: "12",
    motto: "XAVIER ZAIDANE ATHAYA",
    telepon: "081359136708",
    ttl: "JEMBER, 04 JANUARI 2005",
    asal: "JEMBER",
  },
  {
    id: "296",
    nama: "Yan daffa putra liandhie",
    kelompok: "12",
    motto: "Membantu yang ingin dan bisa di bantu",
    telepon: "088230214030",
    ttl: "Lumajang, 19 september 2005",
    asal: "Lumajanh",
  },
];
